<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>miku-cmd</artifactId>

    <parent>
        <groupId>com.miku</groupId>
        <artifactId>miku</artifactId>
        <version>0.0.1</version>
    </parent>

    <packaging>jar</packaging>
    <name>miku-cmd</name>
    <description>miku-cmd</description>

    <dependencies>
        <!-- Core Module -->
        <dependency>
            <groupId>com.miku</groupId>
            <artifactId>miku-core</artifactId>
        </dependency>
        <!-- Other Module -->
        <dependency>
            <groupId>com.miku</groupId>
            <artifactId>miku-demo</artifactId>
        </dependency>

        <!-- Spring Boot Starter -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>com.miku</groupId>
            <artifactId>miku-starter-redis</artifactId>
        </dependency>
    </dependencies>

    <build>
        <finalName>miku-application</finalName>
        <plugins>
            <!-- Spring Boot打包插件 -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <mainClass>com.miku.cmd.MikuApplication</mainClass>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
