spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/miku?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: root
      initial-size: 10
      min-idle: 10
      max-active: 50
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      
# Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: -1ms

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.no.miku.*.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: del_flag
      logic-delete-value: 1
      logic-not-delete-value: 0

# 日志配置
logging:
  level:
    com.no.miku: info


# Starter配置
miku:
  file:
    type: local # 或 oss/minio
    local:
      path: ./file
      enableDirectAccess: true
      tempRetentionHours: 24
      enableTempCleanup: false